### ISSUE TITLE
推荐一个rust的gui库：egui

### ISSUE THREAD

**Issue by LooJee** [RustMagazine/rust_magazine_2022#2]
egui 可以运行在本地和web，感觉还是很酷的，仓库地址：https://github.com/emilk/egui。

**Comment by ZhangHanDong** [comment]
感谢推荐。这个在去年的杂志里也推荐过了。2022的杂志按季度来，如果equi 在这个季度有更新动态，可以收录。不过如果是发 PR 就更好了
